package de.soderer.utilities.db;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import de.soderer.utilities.db.data.DbColumnType;
import de.soderer.utilities.db.data.DbSimpleDataType;
import de.soderer.utilities.db.data.DbStructure;
import de.soderer.utilities.db.data.DbTable;
import de.soderer.utilities.db.data.DbVendor;
import de.soderer.utilities.db.oracle.OracleTnsnamesReader;
import de.soderer.utilities.sql.JoinClause;
import de.soderer.utilities.sql.SelectStatement;
import de.soderer.utilities.sql.SelectStatementFormatter;
import de.soderer.utilities.sql.SqlStatementFormatter;
import de.soderer.utilities.sql.whereclause.ReducedSqlWhereClauseParser;
import de.soderer.utilities.sql.whereclause.token.RulePart;
import de.soderer.utilities.sql.whereclause.token.Value;

/**
 * Regression tests for the bugs found in the code review of October 2026.
 */
@SuppressWarnings("static-method")
@DisplayName("Bugfix regressions")
class BugfixRegressionTest {
	private static InputStream stream(final String text) {
		return new ByteArrayInputStream(text.getBytes(StandardCharsets.UTF_8));
	}

	private static DbTable parseSingleTable(final String ddl, final String tableName) throws Exception {
		final DbStructure structure = SqlDdlParser.parse(stream(ddl));
		return structure.getSchemas().get("").getTables().get(tableName);
	}

	private static String migrate(final String sourceDdl, final String destinationDdl) throws Exception {
		final ByteArrayOutputStream output = new ByteArrayOutputStream();
		SqlDdlMigrationGenerator.diff(stream(sourceDdl), stream(destinationDdl), output);
		return output.toString(StandardCharsets.UTF_8);
	}

	@Test
	@DisplayName("CREATE TABLE with trailing table options is parsed")
	void createTableWithTableOptions() throws Exception {
		assertNotNull(parseSingleTable("CREATE TABLE t (id INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;", "t"));
		assertNotNull(parseSingleTable("CREATE TABLE t (id INT) TABLESPACE users;", "t"));
		final DbTable commented = parseSingleTable("CREATE TABLE t (id INT) ENGINE=InnoDB COMMENT='a (b)';", "t");
		assertEquals("a (b)", commented.getTableComment());
	}

	@Test
	@DisplayName("multi-word column types keep their length")
	void multiWordTypes() throws Exception {
		final DbTable table = parseSingleTable("CREATE TABLE t (n character varying(255) NOT NULL, d double precision, ts timestamp(6) with time zone);", "t");
		final DbColumnType nType = table.getColumns().get("n").getColumnType();
		assertEquals("character varying", nType.getTypeName());
		assertEquals(255, nType.getCharacterByteSize());
		assertEquals("double precision", table.getColumns().get("d").getColumnType().getTypeName());
		assertEquals("timestamp with time zone", table.getColumns().get("ts").getColumnType().getTypeName());
	}

	@Test
	@DisplayName("GENERATED BY DEFAULT AS IDENTITY is no default value")
	void generatedByDefault() throws Exception {
		final DbColumnType type = parseSingleTable("CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY);", "t").getColumns().get("id").getColumnType();
		assertTrue(type.isAutoIncrement());
		assertEquals(null, type.getDefaultValue());
	}

	@Test
	@DisplayName("keywords within string literals are ignored")
	void keywordsInLiterals() throws Exception {
		final DbTable table = parseSingleTable("CREATE TABLE t (id INT COMMENT 'must be NOT NULL and UNIQUE');", "t");
		assertTrue(table.getColumns().get("id").getColumnType().isNullable());
		assertTrue(table.getUniqueKeys().isEmpty());
	}

	@Test
	@DisplayName("ALTER TABLE with IF [NOT] EXISTS and DROP without COLUMN keyword")
	void alterTableVariants() throws Exception {
		final DbTable table = parseSingleTable("CREATE TABLE t (id INT, x INT, y INT);"
				+ " ALTER TABLE t ADD COLUMN IF NOT EXISTS z INT;"
				+ " ALTER TABLE t ADD COLUMN IF NOT EXISTS z INT;"
				+ " ALTER TABLE t DROP COLUMN IF EXISTS unknown;"
				+ " ALTER TABLE t DROP x;", "t");
		assertEquals(Arrays.asList("id", "y", "z"), Arrays.asList(table.getColumns().keySet().toArray()));
	}

	@Test
	@DisplayName("string default values are quoted in generated DDL")
	void defaultValueQuoting() throws Exception {
		final String output = migrate("CREATE TABLE t (n VARCHAR(10));",
				"CREATE TABLE t (n VARCHAR(10) DEFAULT 'abc', k INT DEFAULT 5, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);");
		assertTrue(output.contains("SET DEFAULT 'abc'"), output);
		assertTrue(output.contains("k INT DEFAULT 5"), output);
		assertTrue(output.contains("DEFAULT CURRENT_TIMESTAMP"), output);
	}

	@Test
	@DisplayName("removed comments are reset by IS NULL")
	void removedComment() throws Exception {
		final String output = migrate("CREATE TABLE t (id INT); COMMENT ON TABLE t IS 'x';", "CREATE TABLE t (id INT);");
		assertTrue(output.contains("COMMENT ON TABLE t IS NULL;"), output);
	}

	@Test
	@DisplayName("qualified referenced tables and types without length")
	void mergeOutput() throws Exception {
		final ByteArrayOutputStream output = new ByteArrayOutputStream();
		SqlDdlMergeGenerator.merge(stream("CREATE TABLE s.t (id INT, c VARCHAR, CONSTRAINT fk1 FOREIGN KEY (id) REFERENCES s.u (id));"), stream(""), output);
		final String result = output.toString(StandardCharsets.UTF_8);
		assertTrue(result.contains("REFERENCES s.u (id)"), result);
		assertTrue(result.contains("c VARCHAR,"), result);
	}

	@Test
	@DisplayName("column type classification")
	void simpleDataTypes() {
		assertEquals(DbSimpleDataType.String, new DbColumnType("NVARCHAR", 10, 0, 0, true, false, null).getSimpleDataType());
		assertEquals(DbSimpleDataType.String, new DbColumnType("nchar", 10, 0, 0, true, false, null).getSimpleDataType());
		assertEquals(DbSimpleDataType.Blob, new DbColumnType("VARBINARY", 10, 0, 0, true, false, null).getSimpleDataType());
	}

	@Test
	@DisplayName("key column equations are combined by AND")
	void keyColumnEquations() {
		assertEquals("x.a = y.a AND LOWER(x.b) = LOWER(y.b)", DbUtilities.getKeyColumnEquationList(DbVendor.PostgreSQL, Arrays.asList("a", "LOWER(b)"), "x", "y"));
		assertEquals("a, LOWER(b)", DbUtilities.joinColumnVendorEscaped(DbVendor.PostgreSQL, Arrays.asList("a", "LOWER(b)")));
	}

	@Test
	@DisplayName("reserved words contain no invisible characters")
	void reservedWords() {
		assertTrue(DbUtilities.RESERVED_WORDS_POSTGRESQL.contains("array_max_cardinality"));
		assertTrue(DbUtilities.RESERVED_WORDS_POSTGRESQL.contains("current_default_transform_group"));
	}

	@Test
	@DisplayName("SQLite date values with any number of fraction digits")
	void sqliteFractions() throws Exception {
		assertEquals(LocalDateTime.of(2022, 12, 13, 22, 46, 44, 460515000), DbUtilities.extractSqliteLocalDateTime("2022-12-13T22:46:44.460515"));
		assertEquals(LocalDateTime.of(2022, 12, 13, 22, 46, 44, 460515300), DbUtilities.extractSqliteLocalDateTime("2022-12-13T22:46:44.4605153"));
		assertEquals(LocalDateTime.of(2022, 12, 13, 22, 46, 44, 463491400), DbUtilities.extractSqliteLocalDateTime("2022-12-13T22:46:44.463491400+01:00[Europe/Berlin]"));
	}

	@Test
	@DisplayName("tnsnames.ora with comment lines")
	void tnsnamesComments() throws Exception {
		try (OracleTnsnamesReader reader = new OracleTnsnamesReader(stream("# comment with a=b and (brackets\nXE =\n  # inner comment\n (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = h)(PORT = 1521)) (CONNECT_DATA = (SID = XE)))\n"))) {
			assertTrue(reader.read().containsKey("XE"));
		}
	}

	@Test
	@DisplayName("SelectStatementFormatter output")
	void selectStatementFormatter() throws Exception {
		final SelectStatement statement = new SelectStatement();
		statement.addField("a");
		statement.addFromTable("t");
		statement.setOrderBy(Arrays.asList("a"));
		statement.setJoinClauses(Arrays.asList(new JoinClause("u", "x", JoinClause.JoinType.FullOutterJoin, "x.a = t.a")));
		assertEquals("SELECT a FROM t FULL OUTER JOIN u x ON x.a = t.a ORDER BY a", new SelectStatementFormatter("", "").format(statement));
	}

	@Test
	@DisplayName("SqlStatementFormatter operators and END_DATE identifier")
	void sqlStatementFormatter() {
		assertEquals("SELECT a FROM t WHERE a = 1 AND b >= 2", new SqlStatementFormatter(DbVendor.Oracle, "", "").format("SELECT a FROM t WHERE a=1 AND b>=2"));
		assertFalse(new SqlStatementFormatter().format("SELECT END_DATE FROM t").isEmpty());
	}

	@Test
	@DisplayName("where clause numbers are locale independent and lower() is printable")
	void whereClause() {
		final Locale previousLocale = Locale.getDefault();
		try {
			Locale.setDefault(Locale.GERMANY);
			final Map<String, Value.Type> descriptors = new HashMap<>();
			descriptors.put("a", Value.Type.Number);
			descriptors.put("b", Value.Type.String);
			assertEquals("a = 1000.5", ReducedSqlWhereClauseParser.parse("a = 1000.5", descriptors).toString(RulePart.StringType.Oracle));
			assertEquals("LOWER(b) = 'x'", ReducedSqlWhereClauseParser.parse("lower(b) = 'x'", descriptors).toString(RulePart.StringType.Oracle));
			assertEquals("lower(b) = 'x'", ReducedSqlWhereClauseParser.parse("lower(b) = 'x'", descriptors).toString());
		} finally {
			Locale.setDefault(previousLocale);
		}
	}
}
